// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIvFuYE1QQToyWj_Su6T5_m9l30ZT71_I',
    appId: '1:295311273500:android:095ab1a716f2f599f739d9',
    messagingSenderId: '295311273500',
    projectId: 'vijayapura-tourism-40f3b',
    storageBucket: 'vijayapura-tourism-40f3b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2wvnSmaX8li0xZUKgofLl4iFgBAF9hk',
    appId: '1:295311273500:ios:201e3a58ad2260fcf739d9',
    messagingSenderId: '295311273500',
    projectId: 'vijayapura-tourism-40f3b',
    storageBucket: 'vijayapura-tourism-40f3b.firebasestorage.app',
    iosClientId: '295311273500-sg9hv53f6d1imk3cddb1gmfa7msvdrnh.apps.googleusercontent.com',
    iosBundleId: 'com.vijayapura.tourism.vijayapuraTourism',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWBb-dv2nB1jYwJ2axc1ONI3j00hCeSA',
    appId: '1:295311273500:web:0d7f209d83067ef3f739d9',
    messagingSenderId: '295311273500',
    projectId: 'vijayapura-tourism-40f3b',
    authDomain: 'vijayapura-tourism-40f3b.firebaseapp.com',
    storageBucket: 'vijayapura-tourism-40f3b.firebasestorage.app',
    measurementId: 'G-378WSSWQZ4',
  );
}
